require("./js/egret.js")
require("./js/eui.js")
require("./js/assetsmanager.js")
require("./js/tween.js")
require("./js/default.thm.js")
require("./js/loading.js")
require("./js/main.js")
require("./js/default.thm.js")