// This file is automatically generated by build
window.skins = window.skins || {};
    window.generateEUI = window.generateEUI || {
      paths: {},
      styles: undefined,
      skins: {
	"eui.Button": "resource/eui_skins/ButtonSkin.exml",
	"eui.CheckBox": "resource/eui_skins/CheckBoxSkin.exml",
	"eui.HScrollBar": "resource/eui_skins/HScrollBarSkin.exml",
	"eui.HSlider": "resource/eui_skins/HSliderSkin.exml",
	"eui.Panel": "resource/eui_skins/PanelSkin.exml",
	"eui.TextInput": "resource/eui_skins/TextInputSkin.exml",
	"eui.ProgressBar": "resource/eui_skins/ProgressBarSkin.exml",
	"eui.RadioButton": "resource/eui_skins/RadioButtonSkin.exml",
	"eui.Scroller": "resource/eui_skins/ScrollerSkin.exml",
	"eui.ToggleSwitch": "resource/eui_skins/ToggleSwitchSkin.exml",
	"eui.VScrollBar": "resource/eui_skins/VScrollBarSkin.exml",
	"eui.VSlider": "resource/eui_skins/VSliderSkin.exml",
	"eui.ItemRenderer": "resource/eui_skins/ItemRendererSkin.exml"
},
    };
    require("./eui_skins/ButtonSkin.exml");
require("./eui_skins/CheckBoxSkin.exml");
require("./eui_skins/HScrollBarSkin.exml");
require("./eui_skins/HSliderSkin.exml");
require("./eui_skins/ItemRendererSkin.exml");
require("./eui_skins/PanelSkin.exml");
require("./eui_skins/ProgressBarSkin.exml");
require("./eui_skins/RadioButtonSkin.exml");
require("./eui_skins/ScrollerSkin.exml");
require("./eui_skins/TextInputSkin.exml");
require("./eui_skins/ToggleSwitchSkin.exml");
require("./eui_skins/VScrollBarSkin.exml");
require("./eui_skins/VSliderSkin.exml");
    module.exports = window.generateEUI;
    